---
# === Necessary settings ===
app_git_repository: ""                    # URL репозитория[](https://github.com/user/repo.git)
docker_image_name: ""                     # Полное имя образа (username/appname или registry/repo/app)
docker_username: ""                       # Логин в Docker registry
docker_password: ""                       # Пароль или токен доступа

# === Optional settings ===
app_git_branch: "main"                    # Ветка или тег для сборки
build_temp_dir: "/tmp/ansible-build-{{ ansible_date_time.epoch }}"  # Временная папка для клона
docker_registry_url: "https://index.docker.io/v1/"  # По умолчанию — Docker Hub
docker_platforms: "linux/amd64"           # Платформы для buildx (можно linux/amd64,linux/arm64)
docker_image_tag: "latest"                # Тег образа
buildx_builder_name: "ansible-builder"      # Имя buildx builder (не может быть "default", так как это зарезервированное имя)
cleanup_after_build: true                 # Удалять временную папку после сборки (true/false)